name: Generate Snake Animation

on:
  # Run every 6 hours
  schedule:
    - cron: "0 */6 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        id: snake
        with:
          github_user_name: cyrolux123
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update README with Snake Animation"
          add: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Changes
        uses: ad-m/github-push-action@v0.7.0
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
